# Fase 1 · Análisis Exploratorio de Datos (EDA)

## Objetivo

El objetivo de esta fase es realizar una exploración inicial de los distintos datasets relacionados con la serie de *Friends*, procedentes tanto de fuentes públicas (Kaggle) como de datasets generados y enriquecidos mediante técnicas de IA. Esta revisión permite comprender su estructura, evaluar su calidad y detectar posibles inconsistencias que puedan afectar a las siguientes fases del proyecto.

En esta etapa nos centramos en:

- identificar los datasets disponibles y sus variables principales,
- analizar dimensiones, tipos de datos y coherencia interna,
- detectar valores nulos, duplicados y problemas de calidad,
- explorar variables clave para entender el comportamiento del dataset,
- y anticipar necesidades de limpieza, normalización y transformación.

Este análisis proporciona una base sólida para definir la estrategia de preparación de datos en la fase ETL.

In [1]:
# Configuración del sistema para encontrar la carpeta raíz
import sys
import os

# Esto obliga a Python a mirar una carpeta hacia atrás (donde está 'src')
sys.path.append(os.path.abspath(os.path.join('..')))
sys.path.append(os.path.abspath(os.path.join('.')))

# Importación de librerías
import pandas as pd
import numpy as np

# Importación del módulo de transformación personalizado
from src.etl import transform as trans

# Configuración para visualizar todas las columnas
pd.set_option('display.max_columns', None)

## 1. Carga de los datasets

Se cargan los distintos archivos que contienen información sobre personajes, guiones, temporadas y métricas de diálogo.
Cada uno aporta una dimensión diferente al análisis.

In [2]:
df_bodas_divorcios = pd.read_csv("../data_raw/bodas_divorcios_ross.csv")
df_cameos = pd.read_csv("../data_raw/cameos_friends_completo.csv")
df_emotions = pd.read_csv("../data_raw/friends_emotions.csv")
df_epiv2 = pd.read_csv("../data_raw/friends_episodes_v2.csv")
df_epiv3 = pd.read_csv("../data_raw/friends_episodes_v3.csv", encoding='latin-1')
df_escenarios = pd.read_csv("../data_raw/friends_escenarios.csv")
df_info = pd.read_csv("../data_raw/friends_info.csv")
df_quotes = pd.read_csv("../data_raw/friends_quotes.csv")
df_friends = pd.read_csv("../data_raw/friends.csv")
df_songs = pd.read_csv("../data_raw/phoebe_buffay_songs_v2.csv")
df_pato_pollito = pd.read_csv(
    "../data_raw/apariciones_detalladas_pato_y_pollito(1).csv", 
    sep=';', 
    encoding='latin-1'
)

### Procedemos con la exploración de cada fichero

In [3]:
trans.info_df(df_bodas_divorcios)

Información sobre el dataframe:
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Personaje  6 non-null      str
 1   Evento     6 non-null      str
 2   Temporada  6 non-null      int64
 3   Detalle    6 non-null      str
dtypes: int64(1), str(3)
memory usage: 324.0 bytes
----------------------------------------------------------------------------------------------------
Análisis descriptivo de las variables cualitativas:

          count unique                                    top freq
Personaje     6      3                          Carol Willick    2
Evento        6      2                                   Boda    3
Detalle       6      6  Ocurre antes del piloto (flashbacks).    1

----------------------------------------------------------------------------------------------------
Análisis descriptivo de las variables cuantitativas:

           count  mean  std  min  25%  50%  75%  max
Temporada    6.0   4.0  2.0  0.0  2.0  4.0  5.0  6.0

----------------------------------------------------------------------------------------------------
La forma del dataframe es:
6 filas
4 columnas
----------------------------------------------------------------------------------------------------
Muestra del dataframe:

,Personaje,Evento,Temporada,Detalle
1,Carol Willick,Divorcio,1,Ella descubre que es lesbiana.
4,Rachel Green,Boda,5,Se casan borrachos en Las Vegas.
0,Carol Willick,Boda,0,Ocurre antes del piloto (flashbacks).
3,Emily Waltham,Divorcio,5,Emily le pide no ver a Rachel y él no cumple.
5,Rachel Green,Divorcio,6,Ross intenta ocultar que no tramitó la anulación.