# Fase 2 · Transformación de datos en los datasets

## Objetivo

El objetivo de esta fase consiste en ejecutar los cambios y ajustes detectados durante el Análisis Exploratorio de Datos (EDA), para unificar, limpiar y transformar los datasets seleccionados en este proyecto.

En esta etapa se trabaja principalmente en:

- abordar los duplicados,
- combinar varios datasets,
- gestionar los valores nulos,
- homogenizar categorías para asegurar la integridad semántica,
- y exportar los archivos finales ya depurados.

Este proceso permitirá tener un conjunto de datos más consistentes, comparables y listos para la siguiente fase de análisis avanzado y visualización.

In [8]:
# Importación de librerías
import pandas as pd
import numpy as np
import re

# Configuración del sistema para encontrar la carpeta raíz
import sys
import os

# Esto obliga a Python a mirar una carpeta hacia atrás (donde está 'src')
sys.path.append(os.path.abspath(os.path.join('..')))
sys.path.append(os.path.abspath(os.path.join('.')))

# Importación de módulos de transformación 
from src.etl.load_data import load_friends_data_raw
from src.etl import transform as trans

# Configuración para visualizar todas las columnas del DataFrame
pd.set_option('display.max_columns', None)

In [9]:
dfs = load_friends_data_raw()

[2026-05-22 11:45:20] INFO - Cargando datasets desde: C:\Users\dacil\Desktop\Adalab\pair\modulo_4_pair\friends-analytics-workflow\data_raw
[2026-05-22 11:45:20] INFO - → Cargando bodas_divorcios_ross.csv...
[2026-05-22 11:45:20] INFO - → Cargando cameos_friends_completo.csv...
[2026-05-22 11:45:20] INFO - → Cargando friends_emotions.csv...
[2026-05-22 11:45:20] INFO - → Cargando friends_episodes.csv...
[2026-05-22 11:45:20] INFO - → Cargando friends_escenarios.csv...
[2026-05-22 11:45:20] INFO - → Cargando friends_info.csv...
[2026-05-22 11:45:20] INFO - → Cargando friends_quotes.csv...
[2026-05-22 11:45:20] INFO - → Cargando friends.csv...
[2026-05-22 11:45:21] INFO - → Cargando phoebe_buffay_songs.csv...
[2026-05-22 11:45:21] INFO - → Cargando apariciones_detalladas_pato_y_pollito.csv...
[2026-05-22 11:45:21] INFO - Todos los datasets fueron cargados correctamente.

## 1. Transformación de  las variables numéricas (friends_quotes) de orden de float a entero (int) para mejorar la estructura.

In [10]:
df_quotes = dfs["quotes"]

df_quotes.head()

,author,episode_number,episode_title,quote,quote_order,season
0,Monica,1.0,Monica Gets A Roommate,There's nothing to tell! He's just some guy I ...,0.0,1.0
1,Joey,1.0,Monica Gets A Roommate,"C'mon, you're going out with the guy! There's ...",1.0,1.0
2,Chandler,1.0,Monica Gets A Roommate,"All right Joey, be nice. So does he have a hum...",2.0,1.0
3,Phoebe,1.0,Monica Gets A Roommate,"Wait, does he eat chalk?",3.0,1.0
4,Phoebe,1.0,Monica Gets A Roommate,"Just, 'cause, I don't want her to go through w...",4.0,1.0

In [11]:
df_quotes["quote_order"] = df_quotes["quote_order"].astype(int)
df_quotes["season"] = df_quotes["season"].astype(int)
df_quotes["episode_number"] = df_quotes["episode_number"].astype(int)

In [12]:
df_quotes.head()

,author,episode_number,episode_title,quote,quote_order,season
0,Monica,1,Monica Gets A Roommate,There's nothing to tell! He's just some guy I ...,0,1
1,Joey,1,Monica Gets A Roommate,"C'mon, you're going out with the guy! There's ...",1,1
2,Chandler,1,Monica Gets A Roommate,"All right Joey, be nice. So does he have a hum...",2,1
3,Phoebe,1,Monica Gets A Roommate,"Wait, does he eat chalk?",3,1
4,Phoebe,1,Monica Gets A Roommate,"Just, 'cause, I don't want her to go through w...",4,1

In [ ]:
df_quotes.to_csv("../data_processed/friends_quotes.csv", index=False, encoding="utf-8")

## 2. Limpiar y estandarizar la columna written_by (friends_info)

In [13]:
df_info= dfs["info"]

df_info.head()

,season,episode,title,directed_by,written_by,air_date,us_views_millions,imdb_rating
0,1,1,The Pilot,James Burrows,David Crane & Marta Kauffman,1994-09-22,21.5,8.3
1,1,2,The One with the Sonogram at the End,James Burrows,David Crane & Marta Kauffman,1994-09-29,20.2,8.1
2,1,3,The One with the Thumb,James Burrows,Jeffrey Astrof & Mike Sikowitz,1994-10-06,19.5,8.2
3,1,4,The One with George Stephanopoulos,James Burrows,Alexa Junge,1994-10-13,19.7,8.1
4,1,5,The One with the East German Laundry Detergent,Pamela Fryman,Jeff Greenstein & Jeff Strauss,1994-10-20,18.6,8.5

In [14]:
trans.process_friends_writers(df_info)

¡Fichero corregido con éxito! Guardado en: C:\Users\dacil\Desktop\Adalab\pair\modulo_4_pair\friends-analytics-workflow\data_processed\writters.csv (303 filas).

     season  episode         writter     rol
0         1        1     David Crane  Writer
1         1        1  Marta Kauffman  Writer
2         1        2     David Crane  Writer
3         1        2  Marta Kauffman  Writer
4         1        3  Jeffrey Astrof  Writer
..      ...      ...             ...     ...
298      10       16       Ted Cohen  Writer
299      10       17  Marta Kauffman  Writer
300      10       17     David Crane  Writer
301      10       18  Marta Kauffman  Writer
302      10       18     David Crane  Writer

[303 rows x 4 columns]

In [19]:
df_info.drop("written_by", axis=1, inplace=True)

df_info.head(2)

,season,episode,title,directed_by,air_date,us_views_millions,imdb_rating
0,1,1,The Pilot,James Burrows,1994-09-22,21.5,8.3
1,1,2,The One with the Sonogram at the End,James Burrows,1994-09-29,20.2,8.1

In [20]:
df_quotes.to_csv("../data_processed/friends_info.csv", index=False, encoding="utf-8")